export enum Route {
  base = '',
  home = 'home',
  products = 'products',
  productById = ':id',
  cart = 'cart',
  orders = 'orders',
  about = 'about',
  contact = 'contact',
  wishlist = 'wishlist',
  compare = 'compare',
  faq = 'faq',
  terms = 'terms-and-conditions',
  privacyPolicy = 'privacy-policy',
  cookiePolicy = 'cookie-policy',
  account = 'account',
  trackOrder = 'track-order',
  returns = 'returns-and-exchanges',
  repairServices = 'repair-services',
  support = 'support',
  register = 'register',
  login = 'login',
}
